-- AlterTable
ALTER TABLE "Additional" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Article" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "ArticleType" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "AttendanceControl" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "ClientType" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "CustomizeOrder" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "EmbroideryDetail" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "ExitType" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Gift" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Machine" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "MachineAdditionalCost" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "MachineArticleCost" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Manpower" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "ManpowerAdditional" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "ManpowerMachine" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "MoneyOrder" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "OrderDetail" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "OrderGift" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Person" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Sex" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Size" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "SublimatedDetail" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Supplier" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "UserRoles" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "WorkerType" ALTER COLUMN "dateCreated" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "dateUpdated" SET DATA TYPE TIMESTAMPTZ(6);
